### ISSUE TITLE
Dynamic loading doesn't show the loaded slides

### ISSUE THREAD

**Issue by baigail93** [devmark/ngx-slick#10]
The slides are being added dynamically, although it adds them in the collection but initially it doesn't show anything. If I go to console at `.slick-slide .slick-current .slick-active` element and turn off `display: block` to `display: none` and then turn it on again to `display: block`, it starts to render correctly.

I am using it like 

     <ngx-slick class="carousel" *ngIf="resetSliderPlugin">
          <div ngxSlickItem *ngFor="let galleryImage of galleryImages" class="slide">
              <img [src]="galleryImage.Path" [alt]="galleryImage.Alt" width="100%" />
          </div>
      </ngx-slick>
   

where I have a variable called resetSliderPlugin which is set to true after successfully setting the array (it has the same behavior without this flag).

![screenshot 2017-08-17 03 04 50](https://user-images.githubusercontent.com/28875119/29387402-5298136a-82f9-11e7-9195-b91e9f9e76a8.png)

Any help?

**Comment by devmark** [comment]
Closed. open new issue if any question.
