### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by intergleam** [devmark/ngx-slick#14]
I created a project using [angular cli](https://github.com/angular/angular-cli), followed the steps and this is what I have:
![image](https://user-images.githubusercontent.com/2155554/29773960-66373e92-8c08-11e7-90a6-f28620f32c1a.png)

**Comment by BrsJsk** [comment]
And whats the problem?

**Comment by emmahoggan** [comment]
@intergleam - I'm having this same issue.  The slides are showing and have some styling, but the carousel is not functional. Did you ever determine what was causing the problem?

**Comment by emmahoggan** [comment]
Figured out my issue - it was with the slideConfig variable listed in the sample code.  There are only 4 slides shown in the demo, so `slideConfig = {"slidesToShow": 4, "slidesToScroll": 4};` just shows 4 static slides.  If you change the initial settings to include more options and show fewer slides, you can see the functionality.  E.g., `slideConfig = {"slidesToShow": 2, "slidesToScroll": 2, "dots": true, "infinite": true, "autoplay": true, "autoplaySpeed": 2000};`

**Comment by emmahoggan** [comment]
As a side-note for othes - the other issue it looks like @intergleam and I both had was the fact that we threw the demo on a white background.  Apparently the slick arrows are white by default [()](https://stackoverflow.com/questions/23337972/slick-carousel-arrows-do-not-appear-and-work-as-they-ought-to) so, if you change your background color, the slider also becomes instantly more slider-ish (:

**Comment by devmark** [comment]
Closed. open new issue if any question.
