### ISSUE TITLE
How to achieve autoplay feature?

### ISSUE THREAD

**Issue by akeel214** [devmark/ngx-slick#15]
I want to implement autoplay feature in my slides. How can I achieve this?

**Comment by Marvine89** [comment]
Hi @akeel214,

Might not be the solution but I tried to autoplay the slides on my component using IntervalObservable of rxjs, something like this

**So on your html you have** 
```
<ngx-slick class="carousel" #slickModal="slick-modal" [config]="slideConfig (afterChange)="afterChangedFunction($event)">
      <div ngxSlickItem *ngFor="let img of images; let i = index" class="slide">
        <img src="{{ img.yourImg }}" class="slider-img">
      </div>
</ngx-slick>
```

**On your component import**

`AfterContentInit` from angular/core

`{ IntervalObservable }` from `rxjs/observable/IntervalObservable';`

```
@ViewChild('slickModal') slickModal;
slideConfig = { 'slidesToShow': 1 };
imageSlider_interval:any;
slider_length: number = 0;
current_slide: number = 0;

ngOnDestroy() {
      this.imageSlider_interval.unsubscribe();
}
ngAfterContentInit() {
    this.slider_length = this.slickModal.slides;
   this.imageSlider_interval =  IntervalObservable.create(3500);
   this.slideFunction();
}
slideFunction() {
   this.imageSlider_interval.subscribe( (count) => {
      this.current_slide++;
     if(this.current_slide === this.slider_length - 1) {
         current_slide = 0;
     }
       this.slickModal.slickGoTo(current_slide);
 })
}
afterChangedFunction(event){
  console.log(event)
}
```

**Comment by sam0hack** [comment]
> I want to implement autoplay feature in my slides. How can I achieve this?

Simply add this in your   slideConfig = { autoplay: true, slidesToShow: 4, slidesToScroll: 1 };

more details availabe on https://github.com/devmark/angular-slick-carousel/blob/master/README.md

**Comment by we-for-web** [comment]
@sam0hack Thanks it worked

**Comment by sam0hack** [comment]
🙂
