### ISSUE TITLE
Improve module integration

### ISSUE THREAD

**Issue by jguix** [devmark/ngx-slick#20]
The scripts and CSS references in the index.html shouldn't be necessary.

I am working on a big angular project in which this kind of integration, by putting script and link tags in the index.html is not acceptable.

**Comment by jguix** [comment]
@devmark Please let me know if I can help you moving this issue. Otherwise I will need to search for another similar component.

**Comment by Taewa** [comment]
Hi @jguix 
Which index.html you are talking about?

By the way, did you find another similar component?

**Comment by jguix** [comment]
I was talking about the Installation section of the README, where it states that you should include jquery and ng-slick in the application as so:

Include jquery and slick css/js in your application :
```
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>
<script src="https://unpkg.com/slick-carousel@1.6.0/slick/slick.js"></script>
```

Even though I succeeded to include the library configuring the angular.cli.json instead of modifying the index.html, we finally opted for a different solution.

Alternatives are:
https://github.com/zefoy/ngx-swiper-wrapper
https://github.com/sheikalthaf/ngx-carousel

**Comment by Taewa** [comment]
@jguix 
Ok I see. Mine as well, I had to add them to `angular.cli.json`.

I am experiencing a performance issue because I have 30 ngx-slick in the same page. 
I guess that `this.carousel.addSlide(this);` occurs a lot of re-painting process but not 100% sure. Or I have just too many items.

Thanks for your alternatives!
