### ISSUE TITLE
Multiple ngxSlideItem

### ISSUE THREAD

**Issue by whereo** [devmark/ngx-slick#3]
Is there a way to order the items? I have defined multiple `ngxSlideItem`s (two "normal" slides, and one `for`-loop) and at the moment the slides from the `for`-loop comes first, ignoring the markup in the HTML.
```
<article ngxSlickItem class="slide">
           ...
</article>

<article ngxSlickItem *ngFor="let step of project.steps; let i = index" class="slide">
            ...
</article>

<article ngxSlickItem class="slide">
            ...
</article>
```
Independently from this markup, i always get the slides from the `for`-loop first. Is there a way to change this behaviour?

**Comment by devmark** [comment]
Closed. open new issue if any question.
