### ISSUE TITLE
ngxSlickItem - active class is not getting binding for last two value while using ngFor

### ISSUE THREAD

**Issue by saratkumar** [devmark/ngx-slick#30]
Dynamic array contains 5 data

**this is my slider config**
slideConfig = {slidesToShow: 3,slidesToScroll: 1,draggable:false,infinite:false,dots: false, focusOnSelect: true,nextArrow: '<i class="slick-arrow right icon-caret-right"></i>',prevArrow: '<i class="slick-arrow left icon-caret-left"></i>',};

while doing routing between items works on first three and its not working for last two. slick-active and slick-current class is not getting binding for last 2.

can you please help me out if anything i have done wrong

**Comment by devmark** [comment]
Closed. open new issue if any question.

**Comment by soumikp02** [comment]
the issue still persists
