### ISSUE TITLE
Plan to upgrade to Angular 6?

### ISSUE THREAD

**Issue by sethreidnz** [devmark/ngx-slick#32]
This library doesn't support the latest supported version of Angular. Is there a plan to? If not a plan to put a depreciated warning in the readme?

**Comment by phantomodm** [comment]
I thought so too, but I was able to get this working.. In a vanilla build, it works.. I've placed it in a production project and at first it did not work, then I realized that the directive class="" depends on carousel as the class name..

**Comment by sethreidnz** [comment]
No to worry! There is a replacement https://github.com/leo6104/ngx-slick-carousel

**Comment by sethreidnz** [comment]
Not to worry there is a replacement I found! https://github.com/leo6104/ngx-slick-carousel

**Comment by devmark** [comment]
please try 0.2.0
