### ISSUE TITLE
Uncaught SyntaxError: Unexpected token { 

### ISSUE THREAD

**Issue by Wexx** [devmark/ngx-slick#43]
Just installed this via npm and got it implemented, but I appear to be getting an error on line 1 of the component file (pasted below) at runtime. 

`import { Component, Directive, ElementRef, EventEmitter, Host, Input, NgModule, NgZone, Output, forwardRef } from '@angular/core';`

I declared the SlickModule in my imports array:
`SlickModule.forRoot()`

I'm running Angular CLI 6.1.3. Other than this error everything appears to be working fine.

**Comment by akshaypitale** [comment]
Did you solve this issue ?

**Comment by Wexx** [comment]
I did, we had css conflicts that were causing some strange behavior, and I had the ngxSlickItem attribute on a nested element instead of the repeater. Also verifying the array you're ngFor-ing has to exist.
