### ISSUE TITLE
Cannot find module 'ngx-slick'

### ISSUE THREAD

**Issue by FabienForestier** [devmark/ngx-slick#8]
Hi since the last update of the module, I re-ran the command npm install ngx-slick in my angular 2 application I have this error when I am serving my application "Cannot find module 'ngx-slick'".

Is there an issue with this version of the module?

**Comment by doksides** [comment]
Same here

**Comment by devmark** [comment]
include plugin js already?

Include jquery and slick css/js in your application :
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>
<script src="https://unpkg.com/slick-carousel@1.6.0/slick/slick.js"></script>

**Comment by ert2** [comment]
same issue here. already included

> Include jquery and slick css/js in your application :
><script src="//code.jquery.com/jquery-3.2.1.min.js"></script> <script src="https://unpkg.com>/slick->carousel@1.6.0/slick/slick.js"></script>

**Comment by ert2** [comment]
i downgraded to v0.1.1 now everythings working fine. So it must be an issu with ngx-slick. Usually I suspect the error to be on my side ;)

**Comment by devmark** [comment]
please use 0.1.3.

**Comment by ert2** [comment]
nice, thank you!

**Comment by fdecaminada** [comment]
hi, i have same issue. I run ng serve and throw me this issue 

Error: ENOENT: no such file or directory, open '/Users/facundo/Desktop/xxx-xxx/node_modules/ngx-slick/slick.js'

**Comment by fdecaminada** [comment]
im using version 0.1.3.
