### ISSUE TITLE
$(...).slick is not a function - SystemJS

### ISSUE THREAD

**Issue by baigail93** [devmark/ngx-slick#9]
I am trying to use ngx-slick and am using it with SystemJS. 

In Systemjs.config.js, I added

`map: {
	app: 'app',
	...
	'ngx-slick': 'npm:ngx-slick/ngx-slick.umd.js'
}`

I am using external jQuery in my bundle and have not configured it in the map function. The jQuery file I am adding is defined above the bootstraping 

`<script src="/systemjs.config.js"></script>`
`<script>`
 ` System.import('app').catch(function (err) {`
`  console.error(err);`
`  });`
` </script>`

I get the error in initSlick function which clearly trying to use $ (jQuery reference) which is already loaded. 

![screenshot 2017-08-16 22 36 56](https://user-images.githubusercontent.com/28875119/29376902-94571dd0-82d3-11e7-9b8a-4873074de6d1.png)

Any suggestions?

**Comment by mariobyn** [comment]
Any updates on this?

**Comment by nanduzz** [comment]
same problem here

**Comment by oveshparasara** [comment]
Any updates on this? same problem here

**Comment by DmGolovchenko** [comment]
I added few scripts into .angular-cli file
 "scripts": [
          "../node_modules/jquery/dist/jquery.min.js",
          "../node_modules/slick-carousel/slick/slick.min.js"
 ]
And everything works fine after this.
I hope it helps somehow.

**Comment by kamleshpaliwal-tudip** [comment]
Any update on this?
 $(...).slick is not a function
    at eval (index.js:45)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at NgZone.runOutsideAngular (core.es5.js:4040)
    at SlickComponent.initSlick (index.js:44)
    at SlickComponent.addSlide (index.js:75)
    at SlickItemDirective.ngAfterViewInit (index.js:188)
    at callProviderLifecycles (core.es5.js:11161)
    at callElementProvidersLifecycles (core.es5.js:11136)
    at callLifecycleHooksChildrenFirst (core.es5.js:11120)

**Comment by devmark** [comment]
please try 0.2.0
